CREATE TABLE IF NOT EXISTS USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    GENDER VARCHAR(10),
    PHONE_NUMBER VARCHAR(15),
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(50)
);

INSERT INTO USERS (NAME, GENDER, PHONE_NUMBER, EMAIL, ADDRESS)
VALUES ('John Doe', 'MALE', '123-456-7890', 'john@dccompany.com', '123 Main St');
INSERT INTO USERS (NAME, GENDER, PHONE_NUMBER, EMAIL, ADDRESS)
VALUES ('Jane Smith', 'FEMALE', '987-654-3210', 'jane@dccompany.com', '456 Elm St');
INSERT INTO USERS (NAME, GENDER, PHONE_NUMBER, EMAIL, ADDRESS)
VALUES ('Alice Johnson', 'FEMALE', '555-123-4567', 'alice@dccompany.com', '789 Oak St');
INSERT INTO USERS (NAME, GENDER, PHONE_NUMBER, EMAIL, ADDRESS)
VALUES ('Bob Brown', 'MALE', '444-987-6543', 'bob@dccompany.com', '321 Pine St');
INSERT INTO USERS (NAME, GENDER, PHONE_NUMBER, EMAIL, ADDRESS)
VALUES ('Charlie Davis', 'MALE', '333-222-1111', 'charlie@dccompany.com', '654 Maple St');
INSERT INTO USERS (NAME, GENDER, PHONE_NUMBER, EMAIL, ADDRESS)
VALUES ('Diana Evans', 'FEMALE', '222-333-4444', 'diana@dccompany.com', '987 Cedar St');